name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Deno env
      uses: denolib/setup-deno@master
      with:
        deno-version: 1.x

    - name: Run tests
      run: deno test --allow-read